services:
  postgres:
    image: 'postgres:16-alpine'
    container_name: ddb-postgres
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    ports:
      - '5432:5432'
    volumes:
      - ddb-pgdata:/var/lib/postgresql/data
    restart: always
volumes:
  ddb-pgdata:
    driver: local